### ISSUE TITLE
No Scrolling on Low Resolution

### ISSUE THREAD

**Issue by shinenelson** [Avedo/Cubify#3]
Hey, great plugin. I was looking for a tool to do just this. However, the plugin dialog doesn't scroll when the dialog overflows. Could you look into it?

**Comment by Phidelux** [comment]
Hey, currently there is no option to add scrolling when using the Inkscape UI framework. However, the dialog should be fully expanded so you just have to move it up (on most Systems Alt+Drag) to use it.

**Comment by shinenelson** [comment]
> However, the dialog should be fully expanded so you just have to move it
> up (on most Systems Alt+Click) to use it

I don't understand. I use Inkscape on an Ubuntu machine. And how do I get
about doing whatever you mentioned. And what does it actually do? Can I
view the OK or whatever button you've used to start building the cube?

Thanks

~ shine

**Comment by Phidelux** [comment]
The dialog that is displayed if you start the plugin is written using the Inkscape plugin framework. This framework does not allow the creation of scrolling areas. That means that dialogs created with this framework could be very very long and exceed the edges of your monitor, because they are completely displayed. But you can move the dialog  up and down to see the rest of it. On many systems you could therefore left click on the dialog while holding alt and dragging it. 

Hope this helps you. Would be happy if you share your results.

![cubify_001](https://cloud.githubusercontent.com/assets/1496383/6196827/f14ad540-b3dc-11e4-97ca-30052c4293b9.png)

**Comment by shinenelson** [comment]
Yes, I pretty much know that much. But your dialog was too long that even
pulling up to 768px monitor didn't help.

Instead, I'd give you a suggestion : if it is possible by the Inkscape
Plugin Framework, why don't you dynamically add the fields for commands? As
in, you could add a new field when the user starts typing in one field, or
add a button that puts a field when clicked. That way you could avoid this
kind of a bug. Just suggesting though. Its upto you to decide whether to
implement it in or not.

~ shine

**Comment by Phidelux** [comment]
You shouldn't pull it up to the full screen height, you should pull it over the top (see screenshot). Therefore hold Alt and click into the middle of the dialog, not the titlebar. This also works on Ubuntu.

Regarding your suggestion. It is not possible as the layout gets defined using a xml layout file, which is used by Inkscape to generate the dialog. I just access the input fields from python, I can not dynamically add them.

![workspace 1_003](https://cloud.githubusercontent.com/assets/1496383/6198149/8c6a7e1a-b3f4-11e4-9828-6a75bfbd7941.png)

**Comment by shinenelson** [comment]
Ah. Now I get it. Thanks for pointing me to the feature. I didn't know
there was such a feature for windows at all. The only I knew of dragging
windows were using the title bar. Thanks for the information and your time.

Cheers,

~ shine

**Comment by Phidelux** [comment]
Happy I could help you. Would be great if you share your results here, via twitter [@AvedoNet](https://twitter.com/AvedoNet) or on my website [www.avedo.net](http://avedo.net/915/cubify-the-inkscape-plugin-for-creating-cheat-cubes).

**Comment by shinenelson** [comment]
Sure. Will do that. But I'm kind of busy with other stuff right now. But
whenever I get it done, I'll be sure to share it over to you. :smile:

~ shine

**Comment by su-v** [comment]
You could consider using a second top-level tab (notebook page) for the notebook which at the moment is displayed in the bottom part of the dialog (to keep the overall height of the dialog smaller).

The current dialog is e.g. unusable with smaller screens under OS X (where there is no option to move (via grab & drag, or via keyboard shortcuts) such a dialog window beyond (above, or higher than) the global menubar at the top).

**Comment by shinenelson** [comment]
@su-v, doesn't the alt+drag thing (mentioned in screenshot above by @Avedo
work on Mac OS X? try pressing the alt key and drag the window by clicking
and dragging inside the window, that should work. I'm not sure about Mac OS
X, but it sure works on Ubuntu.

~ shine

**Comment by su-v** [comment]
@shinenelson - OS X ≠ Ubuntu. I typed the comment after testing the dialog of the Cubify extension in Inkscape 0.48.5 and 0.91 on a MBP 13" with OS X 10.7 (with either backend of GTK+) - the native window manager as well as the window manager provided by XQuartz do not support the same keyboard shortcuts to manage windows as provided by the WM on Ubuntu (or any other linux distro). Windows on OS X can only be moved when grabbed and dragged by the title bar (which prevents dragging them above the global menubar at the top). Windows of native apps which have a status bar can also be grabbed and dragged there, but this does not apply to Inkscape (GTK+ app), and even those windows can't be pushed higher than the global menubar.

**Comment by shinenelson** [comment]
> OS X ≠ Ubuntu
> 
> Yes, I know that very well.

I typed the comment after testing the dialog of your extension in Inkscape

> 0.48.5 and 0.91 on a MBP 13" with OS X 10.7 (with either backend of GTK+) -
> the native window manager as well as the window manager provided by XQuartz
> do not support the same keyboard shortcuts to manage windows as provided by
> the WM on Ubuntu (or any other linux distro). Windows on OS X can only be
> moved when grabbed and dragged by the title bar (which prevents dragging
> them above the global menubar at the top).
> 
> (yes, OS X is a proprietary OS, so you don't really have to bother ;-) )
> 
> So, then I'm sorry, I can help you with that anymore. I use a Ubuntu
> machine and do not care about Mac OS. Probably @Avedo could help you out
> here.

~ shine

**Comment by su-v** [comment]
@shinenelson - I was not asking for help, I originally wanted to propose a workaround to @Avedo for the (known) missing 'scrolled window' option in Inkscape's Auto-GUI (the extension dialogs which are created based on the extensions' INX files). Sorry to have missed to correctly address the earlier comment.

**Comment by shinenelson** [comment]
Ah, okay. That'd be great if you could get it done. :smiley:

~ shine

**Comment by Phidelux** [comment]
Hello **su-v**. Thanks for this hint. Didn't think about it. I have updated the layout correspondingly, so you should now be able to use the plugin without any problems under any OS with smaller screens.

![cubify-dialog](https://cloud.githubusercontent.com/assets/1496383/6201126/85bcdf3c-b498-11e4-9cb1-218c267720dc.png)

**Comment by shinenelson** [comment]
That's great @Avedo. Thanks to @su-v for the workaround too. :smiley:

~ shine

**Comment by shinenelson** [comment]
erm. I guess, it still does overflow. But that tolerable. Maybe just on
Ubuntu. But it has made it very much easier to use than before. :blush:

~ shine
