### ISSUE TITLE
Layer structure

### ISSUE THREAD

**Issue by ghost** [Avedo/Cubify#7]
The current structure looks like this:
- Bottom Side
  - Footer
    - Headline Layer
    - Headline Layer
- Footer
  - Headline Layer
  - Headline Layer
- Footer
  - Headline Layer
  - Headline Layer
- Footer
  - Headline Layer
  - Headline Layer
- Footer
  - Headline Layer
  - Headline Layer
- Basic Shape

Those should get individual (and correct) names.
Additionally I'd split the background-object from the border-stroke and put the background(s as of #6) into an additional layer.

At last you should wrap all those layers within a "cube" layer.

**Comment by Phidelux** [comment]
The newest version of Cubify solves this problem.
